apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-mwht
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-mwht
    app.kubernetes.io/part-of: testing-app-1
  name: dc-metro-map-mwht
  namespace: karthik-jk-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: dc-metro-map-mwht
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: dc-metro-map-mwht
    spec:
      containers:
      - image: quay.io/stonesoupuicluster/uidev-user-workload@sha256:58ae94e56296cd767d18dd3328f7d9840d42a0da0d587bdd017cb0a0751883e8
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
