apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-app-multi-components-repo-y2y8
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-app-multi-components-repo-y2y8
    app.kubernetes.io/part-of: testing-app-1
  name: python-app-multi-componenlixq
  namespace: karthik-jk-tenant
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: python-app-multi-components-repo-y2y8
    weight: 100
status: {}
