apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: demo-app-npbb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: demo-app-npbb
    app.kubernetes.io/part-of: testing-app-1
  name: demo-app-npbb
  namespace: karthik-jk-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: demo-app-npbb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: demo-app-npbb
    spec:
      containers:
      - image: quay.io/stonesoupuicluster/uidev-user-workload:tPOTZ-demo-app-npbb
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
